[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200

build_flags =
  -D SERIAL_BAUD=115200
